apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag2-aug26-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag2-aug26-1:c65ec2c2b36292197661089401f0ba5fe05b5903@sha256:6462895f611d61d108c75c88d46046b7a444f0940c89ca7e0d45e0a9f8de0fdf # use pre-built to bootstrap 
          name: app-inference
